source:
  baseUrl: http://localhost/nCoV/api/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${embedded.postgresql.host}:${embedded.postgresql.port}/${embedded.postgresql.schema}
    username: ${embedded.postgresql.user}
    password: ${embedded.postgresql.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
