spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/corov
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


source:
  baseUrl: https://lab.isaaclin.cn/nCoV/api/

management:
  endpoint:
    scheduledtasks:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, scheduledtasks

graphiql:
  enabled: true

