spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    job-store-type: memory

source:
  baseUrl: https://lab.isaaclin.cn/nCoV/api/


