spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  quartz:
    job-store-type: memory

app:
  passphrase: ${PASSPHRASE}

management:
  endpoint:
    scheduledtasks:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, scheduledtasks